//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MU_AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int AttendanceDetailID { get; set; }
        public int AttendanceID { get; set; }
        public int StudentID { get; set; }
        public byte Month { get; set; }
        public byte WeekNumber { get; set; }
        public bool Hour1Present { get; set; }
        public bool Hour2Present { get; set; }
        public bool Hour3Present { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Student Student { get; set; }
    }
}
