//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MU_AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendance()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
        }
    
        public int AttendanceID { get; set; }
        public int StudentID { get; set; }
        public int TeacherID { get; set; }
        public int CourseID { get; set; }
        public int FacultyID { get; set; }
        public int DepartmentID { get; set; }
        public int SemesterID { get; set; }
        public int AcademicYearID { get; set; }
        public System.DateTime StartMonth { get; set; }
        public System.DateTime EndMonth { get; set; }
        public Nullable<int> HoursPresent { get; set; }
        public Nullable<int> HoursAbsent { get; set; }
        public string FinalStatus { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CreatedDate { get; set; }= DateTime.Now;
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Department Department { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
    }
}
