//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MU_AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCours
    {
        public int StudentCourseID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public int FacultyID { get; set; }
        public int DepartmentID { get; set; }
        public int SemesterID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Department Department { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
